name: SeigeWarApproval
version: '1.0-SNAPSHOT'
main: org.ronik.seigeWarApproval.SeigeWarApproval
api-version: '1.20'

commands:
  dma:
    description: DMCA commands
    usage: /dma <approve|disapprove> <player>
    permission: dma.approve
    permission-message: You do not have permission to use this command.
    aliases:
      - SiegeWarApproval
      - swa

permissions:
  dma.approve:
    description: Allows a user to approve a player to start a war.
    default: op

softdepend:
  - PlaceholderAPI

